promocodes:
  promos:
    - promocode: OFFERFIC10
      bookType: TECHNOLOGY
      discount: 10
      expiredate: 28/08/2021
    - promocode: OFFERFIC10
      bookType: SCIENCE
      discount: 0
      expiredate: 12/09/2021
